"""Curated species lists by difficulty tier.

Format: (scientific_name, extra_accepted_aliases)
The canonical display name comes from iNaturalist's preferred common name;
aliases here are EXTRA accepted guesses layered on top of it.
No extinct species, no mythological creatures.
"""

EASY = [
    ("Panthera leo", ["lion"]),
    ("Panthera tigris", ["tiger"]),
    ("Loxodonta africana", ["elephant", "african elephant"]),
    ("Giraffa camelopardalis", ["giraffe"]),
    ("Equus quagga", ["zebra"]),
    ("Ailuropoda melanoleuca", ["panda", "giant panda"]),
    ("Phascolarctos cinereus", ["koala", "koala bear"]),
    ("Macropus giganteus", ["kangaroo"]),
    ("Hippopotamus amphibius", ["hippo", "hippopotamus"]),
    ("Ceratotherium simum", ["rhino", "rhinoceros", "white rhino"]),
    ("Gorilla beringei", ["gorilla"]),
    ("Pan troglodytes", ["chimp", "chimpanzee"]),
    ("Ursus arctos", ["bear", "brown bear", "grizzly", "grizzly bear"]),
    ("Ursus maritimus", ["polar bear"]),
    ("Canis lupus", ["wolf", "grey wolf", "gray wolf"]),
    ("Vulpes vulpes", ["fox", "red fox"]),
    ("Lynx rufus", ["bobcat"]),
    ("Camelus dromedarius", ["camel", "dromedary"]),
    ("Sus scrofa", ["pig", "boar", "wild boar", "hog"]),
    ("Bos taurus", ["cow", "cattle", "bull", "ox"]),
    ("Ovis aries", ["sheep", "lamb", "ram"]),
    ("Capra hircus", ["goat"]),
    ("Equus caballus", ["horse", "pony"]),
    ("Canis familiaris", ["dog", "puppy"]),
    ("Felis catus", ["cat", "house cat", "kitten"]),
    ("Oryctolagus cuniculus", ["rabbit", "bunny"]),
    ("Mus musculus", ["mouse", "house mouse"]),
    ("Rattus norvegicus", ["rat"]),
    ("Sciurus carolinensis", ["squirrel", "grey squirrel", "gray squirrel"]),
    ("Odocoileus virginianus", ["deer", "whitetail deer", "white tailed deer"]),
    ("Alces alces", ["moose", "elk"]),
    ("Procyon lotor", ["raccoon", "racoon"]),
    ("Mephitis mephitis", ["skunk"]),
    ("Erinaceus europaeus", ["hedgehog"]),
    ("Lontra canadensis", ["otter", "river otter"]),
    ("Gallus gallus", ["chicken", "rooster", "hen"]),
    ("Meleagris gallopavo", ["turkey"]),
    ("Anas platyrhynchos", ["duck", "mallard"]),
    ("Cygnus olor", ["swan"]),
    ("Branta canadensis", ["goose", "canada goose"]),
    ("Columba livia", ["pigeon", "dove", "rock dove"]),
    ("Haliaeetus leucocephalus", ["eagle", "bald eagle"]),
    ("Bubo bubo", ["owl", "eagle owl"]),
    ("Spheniscus demersus", ["penguin", "african penguin"]),
    ("Phoenicopterus roseus", ["flamingo"]),
    ("Pavo cristatus", ["peacock", "peafowl"]),
    ("Struthio camelus", ["ostrich"]),
    ("Ara macao", ["macaw", "parrot", "scarlet macaw"]),
    ("Corvus corax", ["raven", "crow"]),
    ("Crocodylus niloticus", ["crocodile", "croc", "nile crocodile"]),
    ("Chelonia mydas", ["turtle", "sea turtle", "green turtle"]),
    ("Naja naja", ["cobra", "snake"]),
    ("Python regius", ["python", "ball python", "snake"]),
    ("Iguana iguana", ["iguana"]),
    ("Rana temporaria", ["frog", "common frog"]),
    ("Tursiops truncatus", ["dolphin", "bottlenose dolphin"]),
    ("Carcharodon carcharias", ["shark", "great white", "great white shark"]),
    ("Octopus vulgaris", ["octopus"]),
    ("Danaus plexippus", ["butterfly", "monarch", "monarch butterfly"]),
    ("Apis mellifera", ["bee", "honeybee", "honey bee"]),
    ("Coccinella septempunctata", ["ladybug", "ladybird"]),
    ("Cornu aspersum", ["snail"]),
    ("Zalophus californianus", ["sea lion", "seal"]),
    ("Megaptera novaeangliae", ["whale", "humpback", "humpback whale"]),
]

MEDIUM = [
    ("Suricata suricatta", ["meerkat"]),
    ("Lemur catta", ["lemur", "ring tailed lemur"]),
    ("Bradypus variegatus", ["sloth", "three toed sloth"]),
    ("Dasypus novemcinctus", ["armadillo"]),
    ("Myrmecophaga tridactyla", ["anteater", "giant anteater"]),
    ("Ornithorhynchus anatinus", ["platypus", "duck billed platypus"]),
    ("Odobenus rosmarus", ["walrus"]),
    ("Bison bison", ["bison", "buffalo"]),
    ("Lama glama", ["llama"]),
    ("Vicugna pacos", ["alpaca"]),
    ("Pongo pygmaeus", ["orangutan", "orang utan"]),
    ("Papio anubis", ["baboon"]),
    ("Acinonyx jubatus", ["cheetah"]),
    ("Panthera pardus", ["leopard"]),
    ("Panthera onca", ["jaguar"]),
    ("Puma concolor", ["puma", "cougar", "mountain lion"]),
    ("Panthera uncia", ["snow leopard"]),
    ("Ailurus fulgens", ["red panda"]),
    ("Lynx lynx", ["lynx"]),
    ("Crocuta crocuta", ["hyena", "spotted hyena"]),
    ("Phacochoerus africanus", ["warthog"]),
    ("Connochaetes taurinus", ["wildebeest", "gnu"]),
    ("Antilocapra americana", ["pronghorn", "antelope"]),
    ("Rangifer tarandus", ["reindeer", "caribou"]),
    ("Bos mutus", ["yak"]),
    ("Hydrochoerus hydrochaeris", ["capybara"]),
    ("Castor canadensis", ["beaver"]),
    ("Erethizon dorsatum", ["porcupine"]),
    ("Tamias striatus", ["chipmunk"]),
    ("Meles meles", ["badger"]),
    ("Mustela putorius", ["ferret", "polecat"]),
    ("Gulo gulo", ["wolverine"]),
    ("Didelphis virginiana", ["opossum", "possum"]),
    ("Vombatus ursinus", ["wombat"]),
    ("Sarcophilus harrisii", ["tasmanian devil"]),
    ("Tachyglossus aculeatus", ["echidna", "spiny anteater"]),
    ("Tapirus terrestris", ["tapir"]),
    ("Herpestes edwardsii", ["mongoose"]),
    ("Vulpes lagopus", ["arctic fox"]),
    ("Canis latrans", ["coyote"]),
    ("Orcinus orca", ["orca", "killer whale"]),
    ("Monodon monoceros", ["narwhal"]),
    ("Trichechus manatus", ["manatee", "sea cow"]),
    ("Fratercula arctica", ["puffin"]),
    ("Ramphastos toco", ["toucan"]),
    ("Pelecanus onocrotalus", ["pelican"]),
    ("Ardea cinerea", ["heron"]),
    ("Ciconia ciconia", ["stork"]),
    ("Grus grus", ["crane"]),
    ("Dromaius novaehollandiae", ["emu"]),
    ("Casuarius casuarius", ["cassowary"]),
    ("Apteryx mantelli", ["kiwi", "kiwi bird"]),
    ("Cacatua galerita", ["cockatoo"]),
    ("Dacelo novaeguineae", ["kookaburra"]),
    ("Gymnogyps californianus", ["condor", "california condor"]),
    ("Falco peregrinus", ["falcon", "peregrine falcon"]),
    ("Dryocopus pileatus", ["woodpecker"]),
    ("Archilochus colubris", ["hummingbird"]),
    ("Phasianus colchicus", ["pheasant"]),
    ("Geococcyx californianus", ["roadrunner"]),
    ("Varanus komodoensis", ["komodo dragon", "komodo"]),
    ("Chamaeleo calyptratus", ["chameleon"]),
    ("Gekko gecko", ["gecko"]),
    ("Alligator mississippiensis", ["alligator", "gator"]),
    ("Crotalus atrox", ["rattlesnake"]),
    ("Boa constrictor", ["boa", "boa constrictor"]),
    ("Ambystoma mexicanum", ["axolotl"]),
    ("Bufo bufo", ["toad"]),
    ("Hippocampus kuda", ["seahorse", "sea horse"]),
    ("Sphyrna mokarran", ["hammerhead", "hammerhead shark"]),
    ("Manta birostris", ["manta ray", "ray", "stingray"]),
    ("Xiphias gladius", ["swordfish"]),
    ("Sepia officinalis", ["cuttlefish"]),
    ("Aurelia aurita", ["jellyfish", "moon jelly"]),
    ("Homarus americanus", ["lobster"]),
    ("Pandinus imperator", ["scorpion", "emperor scorpion"]),
    ("Mantis religiosa", ["praying mantis", "mantis"]),
    ("Anax junius", ["dragonfly"]),
    ("Theraphosa blondi", ["tarantula", "goliath birdeater"]),
    ("Limulus polyphemus", ["horseshoe crab"]),
    ("Asterias rubens", ["starfish", "sea star"]),
    ("Nyctereutes procyonoides", ["raccoon dog", "tanuki"]),
    ("Lycaon pictus", ["african wild dog", "painted dog"]),
    ("Giraffa camelopardalis reticulata", ["reticulated giraffe", "giraffe"]),
    ("Oryx gazella", ["oryx", "gemsbok"]),
    ("Capra ibex", ["ibex"]),
    ("Hylobates lar", ["gibbon"]),
    ("Mandrillus sphinx", ["mandrill"]),
    ("Nasua narica", ["coati", "coatimundi"]),
    ("Marmota flaviventris", ["marmot", "groundhog"]),
    ("Lepus americanus", ["snowshoe hare", "hare"]),
    ("Ochotona princeps", ["pika"]),
    ("Antilope cervicapra", ["blackbuck"]),
    ("Aepyceros melampus", ["impala"]),
    ("Gazella gazella", ["gazelle"]),
    ("Helarctos malayanus", ["sun bear"]),
    ("Ursus americanus", ["black bear"]),
    ("Enhydra lutris", ["sea otter"]),
    ("Pteropus vampyrus", ["fruit bat", "flying fox", "bat"]),
    ("Electrophorus electricus", ["electric eel"]),
    ("Arapaima gigas", ["arapaima"]),
    ("Chrysaora fuscescens", ["sea nettle", "jellyfish"]),
]

HARD = [
    ("Okapia johnstoni", ["okapi"]),
    ("Cryptoprocta ferox", ["fossa"]),
    ("Arctictis binturong", ["binturong", "bearcat"]),
    ("Potos flavus", ["kinkajou"]),
    ("Proteles cristatus", ["aardwolf"]),
    ("Leptailurus serval", ["serval"]),
    ("Caracal caracal", ["caracal"]),
    ("Otocolobus manul", ["pallas cat", "pallas's cat", "manul"]),
    ("Prionailurus viverrinus", ["fishing cat"]),
    ("Herpailurus yagouaroundi", ["jaguarundi"]),
    ("Chrysocyon brachyurus", ["maned wolf"]),
    ("Speothos venaticus", ["bush dog"]),
    ("Cuon alpinus", ["dhole"]),
    ("Eira barbara", ["tayra"]),
    ("Pekania pennanti", ["fisher", "fisher cat"]),
    ("Martes martes", ["pine marten", "marten"]),
    ("Ictonyx striatus", ["zorilla", "striped polecat"]),
    ("Orycteropus afer", ["aardvark"]),
    ("Smutsia gigantea", ["pangolin", "giant pangolin"]),
    ("Procavia capensis", ["hyrax", "rock hyrax", "dassie"]),
    ("Tarsius tarsier", ["tarsier"]),
    ("Nycticebus coucang", ["slow loris", "loris"]),
    ("Otolemur crassicaudatus", ["galago", "bushbaby", "bush baby"]),
    ("Propithecus verreauxi", ["sifaka"]),
    ("Indri indri", ["indri"]),
    ("Daubentonia madagascariensis", ["aye aye", "ayeaye"]),
    ("Nasalis larvatus", ["proboscis monkey"]),
    ("Theropithecus gelada", ["gelada", "gelada baboon"]),
    ("Cacajao calvus", ["uakari", "bald uakari"]),
    ("Alouatta palliata", ["howler monkey", "howler"]),
    ("Symphalangus syndactylus", ["siamang"]),
    ("Pithecia pithecia", ["saki monkey", "saki"]),
    ("Madoqua kirkii", ["dik dik", "dikdik"]),
    ("Litocranius walleri", ["gerenuk"]),
    ("Tragelaphus strepsiceros", ["kudu", "greater kudu"]),
    ("Tragelaphus eurycerus", ["bongo"]),
    ("Oreotragus oreotragus", ["klipspringer"]),
    ("Antidorcas marsupialis", ["springbok"]),
    ("Addax nasomaculatus", ["addax"]),
    ("Saiga tatarica", ["saiga", "saiga antelope"]),
    ("Budorcas taxicolor", ["takin"]),
    ("Capra falconeri", ["markhor"]),
    ("Rupicapra rupicapra", ["chamois"]),
    ("Bos gaurus", ["gaur"]),
    ("Babyrousa celebensis", ["babirusa"]),
    ("Pecari tajacu", ["peccary", "javelina"]),
    ("Muntiacus reevesi", ["muntjac", "barking deer"]),
    ("Hyemoschus aquaticus", ["chevrotain", "water chevrotain", "mouse deer"]),
    ("Pudu puda", ["pudu"]),
    ("Lama guanicoe", ["guanaco"]),
    ("Vicugna vicugna", ["vicuna", "vicuña"]),
    ("Myrmecobius fasciatus", ["numbat"]),
    ("Macrotis lagotis", ["bilby"]),
    ("Setonix brachyurus", ["quokka"]),
    ("Dasyurus viverrinus", ["quoll", "eastern quoll"]),
    ("Petaurus breviceps", ["sugar glider"]),
    ("Galeopterus variegatus", ["colugo", "flying lemur"]),
    ("Condylura cristata", ["star nosed mole", "star-nosed mole"]),
    ("Heterocephalus glaber", ["naked mole rat", "naked mole-rat"]),
    ("Chinchilla lanigera", ["chinchilla"]),
    ("Dolichotis patagonum", ["mara", "patagonian mara"]),
    ("Cuniculus paca", ["paca"]),
    ("Dasyprocta punctata", ["agouti"]),
    ("Jaculus jaculus", ["jerboa"]),
    ("Pedetes capensis", ["springhare", "spring hare"]),
    ("Balaeniceps rex", ["shoebill", "shoebill stork"]),
    ("Opisthocomus hoazin", ["hoatzin"]),
    ("Sagittarius serpentarius", ["secretary bird", "secretarybird"]),
    ("Upupa epops", ["hoopoe"]),
    ("Pharomachrus mocinno", ["quetzal", "resplendent quetzal"]),
    ("Rupicola peruvianus", ["cock of the rock", "cock-of-the-rock"]),
    ("Menura novaehollandiae", ["lyrebird", "superb lyrebird"]),
    ("Ptilonorhynchus violaceus", ["bowerbird", "satin bowerbird"]),
    ("Momotus momota", ["motmot"]),
    ("Podargus strigoides", ["frogmouth", "tawny frogmouth"]),
    ("Nyctibius griseus", ["potoo", "common potoo"]),
    ("Platalea leucorodia", ["spoonbill"]),
    ("Jabiru mycteria", ["jabiru"]),
    ("Eudocimus ruber", ["scarlet ibis", "ibis"]),
    ("Jacana jacana", ["jacana"]),
    ("Eurypyga helias", ["sunbittern"]),
    ("Cariama cristata", ["seriema"]),
    ("Anhinga anhinga", ["anhinga", "snakebird"]),
    ("Rynchops niger", ["skimmer", "black skimmer"]),
    ("Nucifraga columbiana", ["nutcracker", "clarks nutcracker"]),
    ("Sphenodon punctatus", ["tuatara"]),
    ("Gavialis gangeticus", ["gharial", "gavial"]),
    ("Chelus fimbriata", ["matamata", "mata mata"]),
    ("Heloderma suspectum", ["gila monster"]),
    ("Chlamydosaurus kingii", ["frilled lizard", "frilled dragon"]),
    ("Moloch horridus", ["thorny devil", "thorny dragon"]),
    ("Basiliscus plumifrons", ["basilisk", "basilisk lizard", "jesus lizard"]),
    ("Salvator merianae", ["tegu"]),
    ("Proteus anguinus", ["olm"]),
    ("Cryptobranchus alleganiensis", ["hellbender"]),
    ("Necturus maculosus", ["mudpuppy"]),
    ("Pipa pipa", ["surinam toad"]),
    ("Dyscophus antongilii", ["tomato frog"]),
    ("Dendrobates tinctorius", ["poison dart frog", "dart frog"]),
    ("Latimeria chalumnae", ["coelacanth"]),
    ("Polyodon spathula", ["paddlefish"]),
    ("Atractosteus spatula", ["alligator gar", "gar"]),
    ("Mola mola", ["ocean sunfish", "mola", "sunfish"]),
    ("Phycodurus eques", ["leafy sea dragon", "sea dragon"]),
    ("Periophthalmus barbarus", ["mudskipper"]),
    ("Toxotes jaculatrix", ["archerfish", "archer fish"]),
    ("Gnathonemus petersii", ["elephantnose fish", "elephant nose fish"]),
    ("Pristis pristis", ["sawfish"]),
    ("Nautilus pompilius", ["nautilus", "chambered nautilus"]),
    ("Odontodactylus scyllarus", ["mantis shrimp", "peacock mantis shrimp"]),
    ("Glaucus atlanticus", ["blue dragon", "blue sea slug"]),
    ("Spirobranchus giganteus", ["christmas tree worm"]),
    ("Bathynomus giganteus", ["giant isopod"]),
    ("Pycnogonum litorale", ["sea spider"]),
    ("Chiroteuthis veranii", ["deep sea squid", "squid"]),
    ("Architeuthis dux", ["giant squid", "squid"]),
]

DEATH = [
    ("Solenodon paradoxus", ["solenodon", "hispaniolan solenodon"]),
    ("Galemys pyrenaicus", ["pyrenean desman", "desman"]),
    ("Echinosorex gymnura", ["moonrat", "moon rat"]),
    ("Tenrec ecaudatus", ["tenrec", "tailless tenrec"]),
    ("Hemicentetes semispinosus", ["streaked tenrec", "lowland streaked tenrec"]),
    ("Potamogale velox", ["otter shrew", "giant otter shrew"]),
    ("Rhynchocyon petersi", ["sengi", "elephant shrew", "giant elephant shrew"]),
    ("Macroscelides proboscideus", ["round eared sengi", "elephant shrew"]),
    ("Prionodon linsang", ["linsang", "banded linsang"]),
    ("Eupleres goudotii", ["falanouc"]),
    ("Fossa fossana", ["fanaloka", "malagasy civet"]),
    ("Cynogale bennettii", ["otter civet"]),
    ("Arctogalidia trivirgata", ["small toothed palm civet"]),
    ("Melogale moschata", ["ferret badger", "chinese ferret badger"]),
    ("Arctonyx collaris", ["hog badger"]),
    ("Aplodontia rufa", ["mountain beaver"]),
    ("Dinomys branickii", ["pacarana"]),
    ("Myocastor coypus", ["nutria", "coypu"]),
    ("Lagidium viscacia", ["viscacha", "mountain viscacha"]),
    ("Octodon degus", ["degu"]),
    ("Ctenodactylus gundi", ["gundi"]),
    ("Zenkerella insignis", ["scaly tailed squirrel"]),
    ("Anomalurus derbianus", ["scaly tailed flying squirrel"]),
    ("Chaetophractus vellerosus", ["screaming hairy armadillo"]),
    ("Chlamyphorus truncatus", ["pink fairy armadillo", "fairy armadillo"]),
    ("Cyclopes didactylus", ["silky anteater", "pygmy anteater"]),
    ("Bradypus torquatus", ["maned sloth"]),
    ("Naemorhedus goral", ["goral"]),
    ("Capricornis sumatraensis", ["serow", "sumatran serow"]),
    ("Hemitragus jemlahicus", ["tahr", "himalayan tahr"]),
    ("Ovis ammon", ["argali"]),
    ("Ammotragus lervia", ["aoudad", "barbary sheep"]),
    ("Pantholops hodgsonii", ["chiru", "tibetan antelope"]),
    ("Ammodorcas clarkei", ["dibatag"]),
    ("Beatragus hunteri", ["hirola"]),
    ("Dorcatragus megalotis", ["beira"]),
    ("Neotragus pygmaeus", ["royal antelope"]),
    ("Ourebia ourebi", ["oribi"]),
    ("Cephalophus zebra", ["zebra duiker", "duiker"]),
    ("Tragelaphus spekii", ["sitatunga"]),
    ("Tragelaphus angasii", ["nyala"]),
    ("Bubalus mindorensis", ["tamaraw"]),
    ("Bubalus depressicornis", ["anoa", "lowland anoa"]),
    ("Sus cebifrons", ["visayan warty pig", "warty pig"]),
    ("Catagonus wagneri", ["chacoan peccary"]),
    ("Hydropotes inermis", ["chinese water deer", "water deer"]),
    ("Elaphodus cephalophus", ["tufted deer"]),
    ("Elaphurus davidianus", ["pere david's deer", "pere davids deer", "milu"]),
    ("Mazama americana", ["brocket deer", "red brocket"]),
    ("Moschus moschiferus", ["musk deer", "siberian musk deer"]),
    ("Tragulus kanchil", ["lesser mouse deer", "mouse deer", "chevrotain"]),
    ("Tapirus pinchaque", ["mountain tapir", "woolly tapir"]),
    ("Equus kiang", ["kiang"]),
    ("Equus hemionus", ["onager", "asiatic wild ass"]),
    ("Dendrolagus matschiei", ["tree kangaroo", "matschies tree kangaroo"]),
    ("Notoryctes typhlops", ["marsupial mole"]),
    ("Tarsipes rostratus", ["honey possum"]),
    ("Acrobates pygmaeus", ["feathertail glider"]),
    ("Bettongia penicillata", ["woylie", "bettong"]),
    ("Potorous tridactylus", ["potoroo", "long nosed potoroo"]),
    ("Thylogale thetis", ["pademelon", "red necked pademelon"]),
    ("Phalanger orientalis", ["cuscus", "northern common cuscus"]),
    ("Caenolestes fuliginosus", ["shrew opossum"]),
    ("Chironectes minimus", ["water opossum", "yapok"]),
    ("Rhynochetos jubatus", ["kagu"]),
    ("Strigops habroptila", ["kakapo"]),
    ("Porphyrio hochstetteri", ["takahe"]),
    ("Steatornis caripensis", ["oilbird"]),
    ("Brachypteracias leptosomus", ["ground roller", "short legged ground roller"]),
    ("Leptosomus discolor", ["cuckoo roller"]),
    ("Mesitornis variegatus", ["mesite", "white breasted mesite"]),
    ("Philepitta castanea", ["asity", "velvet asity"]),
    ("Heliornis fulica", ["sungrebe"]),
    ("Podica senegalensis", ["finfoot", "african finfoot"]),
    ("Dromas ardeola", ["crab plover"]),
    ("Ibidorhyncha struthersii", ["ibisbill"]),
    ("Pedionomus torquatus", ["plains wanderer"]),
    ("Eupetes macrocerus", ["rail babbler", "malaysian rail babbler"]),
    ("Ifrita kowaldi", ["ifrit", "blue capped ifrit"]),
    ("Chunga burmeisteri", ["black legged seriema"]),
    ("Anhima cornuta", ["horned screamer", "screamer"]),
    ("Scopus umbretta", ["hamerkop"]),
    ("Phoeniculus purpureus", ["wood hoopoe", "green wood hoopoe"]),
    ("Indicator indicator", ["honeyguide", "greater honeyguide"]),
    ("Tichodroma muraria", ["wallcreeper"]),
    ("Picathartes gymnocephalus", ["rockfowl", "picathartes"]),
    ("Todus mexicanus", ["tody", "puerto rican tody"]),
    ("Cephalopterus ornatus", ["umbrellabird", "amazonian umbrellabird"]),
    ("Uroplatus phantasticus", ["satanic leaf tailed gecko", "leaf tailed gecko"]),
    ("Brookesia micra", ["leaf chameleon", "micro chameleon"]),
    ("Lanthanotus borneensis", ["earless monitor lizard", "earless monitor"]),
    ("Bipes biporus", ["mole lizard", "ajolote"]),
    ("Rhineura floridana", ["worm lizard", "amphisbaenian"]),
    ("Acrochordus javanicus", ["elephant trunk snake", "file snake"]),
    ("Atretochoana eiselti", ["caecilian"]),
    ("Typhlonectes natans", ["rubber eel", "caecilian"]),
    ("Andrias japonicus", ["japanese giant salamander", "giant salamander"]),
    ("Siren lacertina", ["siren", "greater siren"]),
    ("Amphiuma means", ["amphiuma", "conger eel"]),
    ("Rhinoderma darwinii", ["darwins frog", "darwin's frog"]),
    ("Nasikabatrachus sahyadrensis", ["purple frog", "pig nosed frog"]),
    ("Telmatobius culeus", ["titicaca water frog", "scrotum frog"]),
    ("Eptatretus stoutii", ["hagfish", "pacific hagfish"]),
    ("Petromyzon marinus", ["lamprey", "sea lamprey"]),
    ("Chlamydoselachus anguineus", ["frilled shark"]),
    ("Mitsukurina owstoni", ["goblin shark"]),
    ("Rhincodon typus", ["whale shark"]),
    ("Regalecus glesne", ["oarfish"]),
    ("Macropinna microstoma", ["barreleye", "barreleye fish"]),
    ("Himantolophus groenlandicus", ["anglerfish", "footballfish"]),
    ("Chauliodus sloani", ["viperfish"]),
    ("Anoplogaster cornuta", ["fangtooth"]),
    ("Psychrolutes marcidus", ["blobfish"]),
    ("Brachionichthys hirsutus", ["handfish", "spotted handfish"]),
    ("Antennarius maculatus", ["frogfish", "warty frogfish"]),
    ("Synanceia verrucosa", ["stonefish"]),
    ("Uranoscopus scaber", ["stargazer"]),
    ("Polypterus senegalus", ["bichir", "senegal bichir"]),
    ("Protopterus annectens", ["lungfish", "african lungfish"]),
    ("Peripatus juliformis", ["velvet worm"]),
    ("Milnesium tardigradum", ["tardigrade", "water bear"]),
    ("Clione limacina", ["sea angel", "sea butterfly"]),
    ("Pyrosoma atlanticum", ["pyrosome"]),
    ("Salpa fusiformis", ["salp"]),
    ("Physalia physalis", ["portuguese man o war", "man o war"]),
    ("Beroe cucumis", ["comb jelly", "ctenophore"]),
    ("Gorgonocephalus eucnemis", ["basket star"]),
    ("Metacrinus rotundus", ["sea lily", "crinoid"]),
    ("Antedon bifida", ["feather star", "crinoid"]),
    ("Enypniastes eximia", ["sea cucumber", "headless chicken monster"]),
    ("Priapulus caudatus", ["penis worm", "priapulid"]),
    ("Sipunculus nudus", ["peanut worm", "sipunculid"]),
    ("Ptychodera flava", ["acorn worm", "yellow acorn worm"]),
    ("Alpheus randalli", ["pistol shrimp", "snapping shrimp"]),
    ("Eunice aphroditois", ["bobbit worm"]),
    ("Lepidopus caudatus", ["scabbardfish"]),
    ("Argonauta argo", ["argonaut", "paper nautilus"]),
    ("Vampyroteuthis infernalis", ["vampire squid"]),
    ("Grimpoteuthis discoveryi", ["dumbo octopus"]),
]

TIERS = {"easy": EASY, "medium": MEDIUM, "hard": HARD, "death": DEATH}
